import 'package:flutter/widgets.dart';

import 'lit_icon_data.dart';

/// The IconData objects used to implement the LitIcons.

class LitIcons {
  LitIcons._();
  static const IconData chevron_right = LitIconData(0xe800);
  static const IconData chevron_right_solid = LitIconData(0xe801);
  static const IconData chevron_left = LitIconData(0xe802);
  static const IconData chevron_left_solid = LitIconData(0xe803);
  static const IconData diary = LitIconData(0xe804);
  static const IconData diary_alt = LitIconData(0xe805);
  static const IconData disk = LitIconData(0xe806);
  static const IconData disk_alt = LitIconData(0xe807);
  static const IconData gear = LitIconData(0xe808);
  static const IconData gear_solid = LitIconData(0xe809);
  static const IconData heart = LitIconData(0xe80a);
  static const IconData heart_solid = LitIconData(0xe80b);
  static const IconData home = LitIconData(0xe80c);
  static const IconData home_alt = LitIconData(0xe80d);
  static const IconData info = LitIconData(0xe80e);
  static const IconData moon = LitIconData(0xe80f);
  static const IconData moon_solid = LitIconData(0xe810);
  static const IconData moon_with_stars = LitIconData(0xe811);
  static const IconData moon_with_stars_solid = LitIconData(0xe812);
  static const IconData plus = LitIconData(0xe813);
  static const IconData times = LitIconData(0xe814);
  static const IconData animation = LitIconData(0xe815);
  static const IconData arrow_right = LitIconData(0xe816);
  static const IconData arrow_right_solid = LitIconData(0xe817);
  static const IconData arrow_left = LitIconData(0xe818);
  static const IconData arrow_left_solid = LitIconData(0xe819);
  static const IconData check = LitIconData(0xe81a);
  static const IconData rgb_solid = LitIconData(0xe81b);
  static const IconData pencil = LitIconData(0xe81c);
  static const IconData pencil_alt = LitIconData(0xe81d);
  static const IconData mix = LitIconData(0xe81e);
  static const IconData rgb = LitIconData(0xe81f);
  static const IconData photos = LitIconData(0xe820);
  static const IconData map_marker = LitIconData(0xe821);
  static const IconData person_solid = LitIconData(0xe822);
  static const IconData person = LitIconData(0xe823);
  static const IconData quote_right = LitIconData(0xe824);
  static const IconData quote_left = LitIconData(0xe825);
  static const IconData bolt = LitIconData(0xe827);
  // static const IconData document_solid = LitIconData(0xe800);
  // static const IconData disk = LitIconData(0xe801);
  // static const IconData disk_solid = LitIconData(0xe802);
  // static const IconData diary = LitIconData(0xe803);
  // static const IconData diary_solid = LitIconData(0xe804);
  // static const IconData chevron_right_solid = LitIconData(0xe805);
  // static const IconData chevron_right = LitIconData(0xe806);
  // static const IconData check = LitIconData(0xe807);
  // static const IconData check_circle = LitIconData(0xe808);
  // static const IconData check_solid = LitIconData(0xe809);
  // static const IconData arrow_right_solid = LitIconData(0xe80a);
  // static const IconData arrow_right = LitIconData(0xe80b);
  // static const IconData arrow_left_solid = LitIconData(0xe80c);
  // static const IconData animation = LitIconData(0xe80d);
  // static const IconData arrow_left = LitIconData(0xe80e);
  // static const IconData moon = LitIconData(0xe80f);
  // static const IconData moon_with_stars = LitIconData(0xe810);
  // static const IconData moon_solid = LitIconData(0xe811);
  // static const IconData moon_with_stars_solid = LitIconData(0xe812);
  // static const IconData chevron_left = LitIconData(0xe813);
  // static const IconData chevron_left_solid = LitIconData(0xe814);
  // static const IconData times = LitIconData(0xe815);
  // static const IconData times_solid = LitIconData(0xe816);
  // static const IconData plus = LitIconData(0xe817);
  // static const IconData plus_solid = LitIconData(0xe818);
  // static const IconData minus = LitIconData(0xe819);
  // static const IconData minus_solid = LitIconData(0xe81a);
  // static const IconData heart = LitIconData(0xe81b);
  // static const IconData info = LitIconData(0xe81c);
  // static const IconData gear_solid = LitIconData(0xe81d);
  // static const IconData gear = LitIconData(0xe81e);
  // static const IconData document = LitIconData(0xe81f);
  // static const IconData heart_solid = LitIconData(0xe820);
  // static const IconData info_solid = LitIconData(0xe821);
}
