/// Contains all keys that map to a localized value.
///
/// The keys on the localization map are accessed using it's corresponding
/// [LeitmotifLocalizationsKeys] property to enforce integrity.
class LeitmotifLocalizationsKeys {
  const LeitmotifLocalizationsKeys();
  static const String submitLabel = 'submitLabel';
  static const String applyLabel = 'applyLabel';
  static const String cancelLabel = 'cancelLabel';
  static const String startLabel = 'startLabel';
  static const String selectLabel = 'selectLabel';
  static const String resetLabel = 'resetLabel';
  static const String backLabel = 'backLabel';
  static const String dateInputLabel = 'dateInputLabel';
  static const String colorInputLabel = 'colorInputLabel';
  static const String ageInputLabel = 'ageInputLabel';
  static const String ageRequiredLabel = 'ageRequiredLabel';
  static const String dayOfWeek1 = 'dayOfWeek1';
  static const String dayOfWeek2 = 'dayOfWeek2';
  static const String dayOfWeek3 = 'dayOfWeek3';
  static const String dayOfWeek4 = 'dayOfWeek4';
  static const String dayOfWeek5 = 'dayOfWeek5';
  static const String dayOfWeek6 = 'dayOfWeek6';
  static const String dayOfWeek7 = 'dayOfWeek7';
  static const String january = 'january';
  static const String february = 'february';
  static const String march = 'march';
  static const String april = 'april';
  static const String may = 'may';
  static const String june = 'june';
  static const String july = 'july';
  static const String august = 'august';
  static const String september = 'september';
  static const String october = 'october';
  static const String november = 'november';
  static const String december = 'december';
  static const String yourAgeLabel = 'yourAgeLabel';
  static const String invalidInputLabel = 'invalidInputLabel';
  static const String invalidInputBody = 'invalidInputBody';
  static const String invalidInputExtendedBody = 'invalidInputExtendedBody';
  static const String verifyAgeScreenSuccessTitle =
      'verifyAgeScreenSuccessTitle';
  static const String verifyAgeScreenSuccessSubtitle =
      'verifyAgeScreenSuccessSubtitle';
  static const String verifyAgeScreenSuccessBody = 'verifyAgeScreenSuccessBody';
  static const String verifyAgeScreenDescriptionBody =
      'verifyAgeScreenDescriptionBody';
  static const String creditsLabel = 'creditsLabel';
  static const String fullyTransparentLabel = 'fullyTransprentLabel';
  static const String licensesLabel = 'licensesLabel';
  static const String notificationLabel = 'notificationLabel';
  static const String advancedSettingsLabel = 'advancedSettingsLabel';
  static const String settingsLabel = 'settingsLabel';
  static const String nextLabel = 'nextLabel';
  static const String onboardingLabel = 'onboardingLabel';
  static const String dismissLabel = 'dismissLabel';
  static const String signUpLabel = 'signUpLabel';
  static const String privacyPolicyLabel = 'privacyPolicyLabel';
  static const String privacyLabel = 'privacyLabel';
  static const String privateLabel = 'privateLabel';
  static const String offlineLabel = 'offlineLabel';
  static const String agreeLabel = 'agreeLabel';
  static const String deleteLabel = 'deleteLabel';
  static const String deleteDescriptionBodyText = 'deleteDescriptionBodyText';
  static const String deleteObjectTitle = 'deleteObjectTitle';
  static const String confirmDeleteTitle = 'confirmDeleteTitle';
  static const String deleteObjectPrompt = 'deleteObjectPrompt';
  static const String composeLabel = 'composeLabel';
  static const String createLabel = 'createLabel';
  static const String aboutAppLabel = 'aboutAppLabel';
  static const String userExpericenceDesignLabel = 'uxDesignLabel';
  static const String developmentLabel = 'developmentLabel';
  static const String photographyLabel = 'photographyLabel';
  static const String manageBackupLabel = 'manageBackupLabel';
  static const String startTourLabel = 'startTourLabel';
  static const String creatorLabel = 'creatorLabel';
  static const String allLabel = 'allLabel';
  static const String latestLabel = 'latestLabel';
  static const String unsavedLabel = 'unsavedLabel';
  static const String restoreDiaryTitle = 'restoreDiaryTitle';
  static const String restoreLabel = 'restoreLabel';
  static const String savedLabel = 'savedLabel';
  static const String locationLabel = 'locationLabel';
  static const String publishedLabel = 'publishedLabel';
  static const String statisticsLabel = 'statisticsLabel';
  static const String selectBackupTitle = 'selectBackupTitle';
  static const String restoreFromBackupTitle = 'restoreFromBackupTitle';
  static const String unsupportedFileTitle = 'unsupportedFileTitle';
  static const String unsupportedFileDescr = 'unsupportedFileDescr';
  static const String createdOnLabel = 'createdLabel';
  static const String moreLabel = 'moreLabel';
  static const String lessLabel = 'lessLabel';
  static const String todayLabel = 'todayLabel';
  static const String anotherDayLabel = 'anotherDayLabel';
  static const String pickFileLabel = 'pickFileLabel';
  static const String selectedLabel = 'selectedLabel';
  static const String upToDateLabel = 'upToDateLabel';
  static const String unsavedChangesLabel = 'unsavedChangesLabel';
  static const String discardLabel = 'discardLabel';
  static const String discardDesc = 'discardDesc';
  static const String confirmDiscardActionDescr = 'confirmDiscardActionDescr';
}
